-- MySQL Script generated by MySQL Workbench
-- Wed Mar 29 23:27:37 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema agenciaautos
-- -----------------------------------------------------
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Auto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Auto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Auto` (
  `numeroPlacas` INT NOT NULL,
  `marca` VARCHAR(45) NULL,
  `anio` INT NULL,
  `modelo` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`numeroPlacas`, `Cliente_idCliente`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cliente` (
  `idCliente` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Entrega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Entrega` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Entrega` (
  `idEntrega` INT NOT NULL,
  `nomUsuario` VARCHAR(45) NULL,
  `fechaEntrega` DATE NULL,
  `proximoServicio` DATE NULL,
  PRIMARY KEY (`idEntrega`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Refaccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Refaccion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Refaccion` (
  `idRefaccion` INT NOT NULL,
  `modelo` VARCHAR(45) NULL,
  `marca` VARCHAR(45) NULL,
  `pieza` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idRefaccion`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Servicio` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Servicio` (
  `idServicio` INT NOT NULL,
  `fechaIngreso` DATE NULL,
  `tipoServicio` VARCHAR(45) NULL,
  `descripcion` VARCHAR(100) NULL,
  `estatus` VARCHAR(45) NULL,
  `Auto_numeroPlacas` INT NOT NULL,
  `Auto_Cliente_idCliente` INT NOT NULL,
  `Entrega_idEntrega` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idServicio`, `Auto_numeroPlacas`, `Auto_Cliente_idCliente`, `Entrega_idEntrega`, `Usuario_idUsuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Servicio_has_Refaccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Servicio_has_Refaccion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Servicio_has_Refaccion` (
  `Servicio_idServicio` INT NOT NULL,
  `Servicio_Auto_numeroPlacas` INT NOT NULL,
  `Servicio_Auto_Cliente_idCliente` INT NOT NULL,
  `Servicio_Entrega_idEntrega` INT NOT NULL,
  `Servicio_Usuario_idUsuario` INT NOT NULL,
  `Refaccion_idRefaccion` INT NOT NULL,
  PRIMARY KEY (`Servicio_idServicio`, `Servicio_Auto_numeroPlacas`, `Servicio_Auto_Cliente_idCliente`, `Servicio_Entrega_idEntrega`, `Servicio_Usuario_idUsuario`, `Refaccion_idRefaccion`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Usuario` (
  `idUsuario` INT NOT NULL,
  `nomUsuario` VARCHAR(45) NULL,
  `contrasena` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
